from datetime import date
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, field_validator


class Link(BaseModel):
    """An external link. label is what shows; url is where it goes."""

    model_config = ConfigDict(extra="forbid")

    label: str
    url: str


class Story(BaseModel):
    """Fields every desk shares. Never instantiated directly."""

    model_config = ConfigDict(extra="forbid")

    title: str
    dek: str | None = None
    date: date
    weight: int = 10
    column_one: bool = False         # promote to the left-hand feature column
    hero: str | None = None
    hero_caption: str | None = None
    hero_focus: str = "50% 50%"      # object-position: what the crop keeps
    dateline: str | None = None      # None -> the paper's own city
    correction: str | None = None
    tags: list[str] = Field(default_factory=list)
    links: list[Link] = Field(default_factory=list)   # external: GitHub, LinkedIn, a demo
    draft: bool = False

    # Filled in by the loader, not by frontmatter.
    slug: str = ""
    body: str = ""

    @property
    def url(self) -> str:
        return f"/{self.section}/{self.slug}/"


class Dispatch(Story):
    """Writing. The section becomes the URL prefix."""

    section: Literal["software", "op-ed", "lab-notes"] = "lab-notes"
    # slug of a workshop project this piece is about. The connection is declared
    # HERE, once; the project page discovers its related posts by asking who
    # points at it. One direction of truth, so the two can never disagree.
    about: str | None = None


class Project(Story):
    """Things on the bench."""

    section: Literal["workshop"] = "workshop"
    status: Literal["live", "in progress", "shelved", "shipped"] = "in progress"
    about: None = None                # projects never point at themselves; here so
                                      #   the shared article template can ask safely
    stack: list[str] = Field(default_factory=list)
    link: str | None = None


class Obituary(Story):
    """Things that died. The schema will not let you be vague about why."""

    section: Literal["obituaries"] = "obituaries"
    born: date
    died: date
    cause_of_death: str


class Car(BaseModel):
    """One car in the collection. These come from content/motoring.yaml — a
    catalogue is data, not writing, so it does not get a file each."""

    model_config = ConfigDict(extra="forbid")

    name: str
    issued: int                      # year the casting was issued
    acquired: date                   # written YYYY-MM; the day is not remembered
    image: str
    description: str = ""
    series: str | None = None
    scale: str = "1:64"

    @field_validator("acquired", mode="before")
    @classmethod
    def _month_is_enough(cls, v):
        """Accept 2026-05 and mean May 2026. Nobody remembers the day."""
        if isinstance(v, str) and len(v) == 7 and v[4] == "-":
            return v + "-01"
        return v

    @property
    def slug(self) -> str:
        return "".join(c if c.isalnum() else "-" for c in self.name.lower()).strip("-")


class Photograph(BaseModel):
    """One frame. A photograph that needs a data table is not a photograph, so
    this has a caption and nothing else."""

    model_config = ConfigDict(extra="forbid")

    image: str
    caption: str


class Pick(BaseModel):
    """One thing the editor likes. A list of favourites is a data export; a
    one-line verdict on each is a critic's page. The verdict is the section."""

    model_config = ConfigDict(extra="forbid")

    kind: Literal["film", "book", "record"]
    title: str
    by: str                          # director / author / artist
    year: int | None = None
    note: str = ""
    star: bool = False               # eligible for the standing recommendation
    # The dek claims this critic has never given an unfavourable notice. The
    # schema enforces it. Loosen to ge=1 if you ever grow the courage.
    stars: int = Field(5, ge=4, le=5)


class Cell(BaseModel):
    """One white square. Generated by tools/crossword.py, never hand-written."""

    model_config = ConfigDict(extra="forbid")

    x: int
    y: int
    a: str                           # the answer letter
    n: int | None = None             # clue number, if a word starts here


class Clue(BaseModel):
    model_config = ConfigDict(extra="forbid")

    n: int
    clue: str
    answer: str


class Puzzle(BaseModel):
    model_config = ConfigDict(extra="forbid")

    number: int
    cols: int
    rows: int
    cells: list[Cell]
    across: list[Clue]
    down: list[Clue]


class Cartoon(BaseModel):
    """The editorial cartoon. image is optional on purpose: a cartoon you did
    not draw is not your cartoon, so the paper would rather print an apology."""

    model_config = ConfigDict(extra="forbid")

    caption: str
    image: str | None = None